# Generated by Django 2.0.5 on 2018-06-07 17:46

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('start', models.DateTimeField(verbose_name='Start Date')),
                ('end', models.DateTimeField(verbose_name='End Date')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Reason')),
                ('status', models.CharField(blank=True, choices=[('1', 'Approved'), ('3', 'Pending'), ('2', 'Rejected')], default='3', max_length=1, verbose_name='Status')),
                ('comments', models.TextField(blank=True, default='', verbose_name='Comments')),
            ],
            options={
                'verbose_name': 'Leave',
                'verbose_name_plural': 'Leave',
                'ordering': ['staff', 'start'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OverTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('start', models.DateTimeField(verbose_name='Start Date')),
                ('end', models.DateTimeField(verbose_name='End Date')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Reason')),
                ('status', models.CharField(blank=True, choices=[('1', 'Approved'), ('3', 'Pending'), ('2', 'Rejected')], default='3', max_length=1, verbose_name='Status')),
                ('comments', models.TextField(blank=True, default='', verbose_name='Comments')),
            ],
            options={
                'verbose_name': 'Overtime',
                'verbose_name_plural': 'Overtime',
                'ordering': ['staff', 'start'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('file', private_storage.fields.PrivateFileField(help_text='Upload staff member drocument', storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='staff-documents/', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Staff Document',
                'verbose_name_plural': 'Staff Documents',
                'ordering': ['staff', 'name', 'created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('sex', models.CharField(blank=True, choices=[('0', 'Not Known'), ('1', 'Male'), ('2', 'Female'), ('9', 'Not Applicable')], default='0', max_length=1, verbose_name='Gender')),
                ('birthday', models.DateField(blank=True, default=None, null=True, verbose_name='Birth day')),
                ('leave_days', models.PositiveIntegerField(blank=True, default=21, help_text='Number of leave days allowed in a year.', verbose_name='Leave days')),
                ('overtime_allowed', models.BooleanField(default=False, verbose_name='Overtime allowed')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Data')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'ordering': ['user__first_name', 'user__last_name', 'user__username', 'created'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='staffdocument',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='small_small_hr.StaffProfile', verbose_name='Staff Member'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='small_small_hr.StaffProfile', verbose_name='Staff Member'),
        ),
        migrations.AddField(
            model_name='leave',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='small_small_hr.StaffProfile', verbose_name='Staff Member'),
        ),
    ]
