# Generated by Django 3.0.7 on 2020-06-07 19:44
# pylint: disable=invalid-name,missing-module-docstring,missing-class-docstring
import django.db.models.deletion
from django.db import migrations, models

import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("small_small_hr", "0008_auto_20200607_1537"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="level",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="lft",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="rght",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="supervisor",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="small_small_hr.StaffProfile",
                verbose_name="Supervisor",
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
